version: 0.2
env:
  secrets-manager:
    SOURCE_SERVER_NAME: $SECRET_ARN_1:POSTGRES_HOST
    SOURCE_DATABASE_NAME: $SECRET_ARN_1:POSTGRES_DATABASE
    SOURCE_USERNAME: $SECRET_ARN_1:POSTGRES_USER
    SOURCE_PASSWORD: $SECRET_ARN_1:POSTGRES_PASSWORD
    TARGET_SERVER_NAME: $SECRET_ARN_2:POSTGRES_HOST
    TARGET_DATABASE_NAME: $SECRET_ARN_2:POSTGRES_DATABASE
    TARGET_USERNAME: $SECRET_ARN_2:POSTGRES_USER
    TARGET_PASSWORD: $SECRET_ARN_2:POSTGRES_PASSWORD
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g pg-compare
      # - wget https://s3.amazonaws.com/publicsctdownload/Ubuntu/aws-schema-conversion-tool-1.0.latest.zip
      # - unzip aws-schema-conversion-tool-1.0.latest.zip
      # - sudo dpkg -i aws-schema-conversion-tool-1.0.latest/aws-schema-conversion-tool-1.0.build-number.deb
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo Installing source NPM pg-compare...
      - ls
      - echo Modifying pg-compare Schema
      - sudo cp -r pg-compare/Schema.js /usr/local/lib/node_modules/pg-compare/lib
      - echo "Executing Terraform Init"
      - cd terraform
      - terraform init -backend-config="bucket=pg-compare-terraform" -backend-config="key=my-state-file.tfstate" -backend-config="region=us-east-1"
      - cd ..
      - ls

  build:
    commands:
      - echo Execute Main AWS DBs Migration
      - ./aws_dms_migration.sh 
  post_build:
    commands:
      - echo Build completed on `date`  
