version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14
    commands:
      - npm install -g pg-compare
  pre_build:
    commands:
      - echo Installing source NPM pg-compare...
      - ls
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`  
