version: 0.2
env:
  secrets-manager:
    SOURCE_SERVER_NAME: $SECRET_ARN_1:POSTGRES_HOST
    SOURCE_DATABASE_NAME: $SECRET_ARN_1:POSTGRES_DATABASE
    SOURCE_USERNAME: $SECRET_ARN_1:POSTGRES_USER
    SOURCE_PASSWORD: $SECRET_ARN_1:POSTGRES_PASSWORD
    TARGET_SERVER_NAME: $SECRET_ARN_2:POSTGRES_HOST
    TARGET_DATABASE_NAME: $SECRET_ARN_2:POSTGRES_DATABASE
    TARGET_USERNAME: $SECRET_ARN_2:POSTGRES_USER
    TARGET_PASSWORD: $SECRET_ARN_2:POSTGRES_PASSWORD
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g pg-compare
      - sudo sed -i '2 s/^/# /' /etc/apt/sources.list
      - apt install make curl postgresql-client-14 -y
      - echo "Installing Terraform"
      - curl -o terraform.zip https://releases.hashicorp.com/terraform/0.15.5/terraform_0.15.5_linux_amd64.zip
      - unzip terraform.zip -d /usr/local/bin/
      - terraform --version
  pre_build:
    commands:
      - echo Installing source NPM pg-compare...
      - ls
      - echo Modifying pg-compare Schema
      - sudo cp -r pg-compare/Schema.js /usr/local/lib/node_modules/pg-compare/lib
      - echo 'compareDB.json' |
          jq --arg source_host "${env.SOURCE_SERVER_NAME}" '.connection1.host = \$source_host' |
          jq --arg source_db "${env.SOURCE_DATABASE_NAME}" '.connection1.database = \$source_db' |
          jq --arg source_user "${env.SOURCE_USERNAME}" '.connection1.user = \$source_user' |
          jq --arg source_pw "${env.SOURCE_PASSWORD}" '.connection1.password = \$source_pw' |
          jq --arg target_host "${env.TARGET_SERVER_NAME}" '.connection2.host = \$target_host' |
          jq --arg target_db "${env.TARGET_DATABASE_NAME}" '.connection2.database = \$target_db' |
          jq --arg target_user "${env.TARGET_USERNAME}" '.connection2.user = \$target_user' |
          jq --arg target_pw "${env.TARGET_PASSWORD}" '.connection2.password = \$target_pw' |
          jq
      - cat compareDB.json
      - cd ..
      - ls

  build:
    commands:
    # Tests 1
      - echo Execute pg-compare
      - echo Conditional PG Compare
      - echo pg_dump if it's necessary

  post_build:
    commands:
      - echo Build completed on `date`  
